# Site Settings
name: Apocalypse's Dungeon
title: Apocalypse's Dungeon
description: 아포칼립스의 잡동사니 저장소
tags:
  - blog
  - tech
  - programming
  - game
email: psj89220@gmail.com
disqus_username: apocalypse
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Tags
    url: /tags
  - title: Contact
    url: /contact
  - title: Feed
    url: /feed.xml


# Social Media Settings
# Remove the item if you don't need it
github_username: psj89220
facebook_username: psj89220@naver.com
twitter_username: psj89220
# instagram_username: instagram_username
# linkedin_username: linkedin_username
# medium_username: medium_username


# Posts Settings
show_time_bar: true
show_modal_on_exit: true
show_modal_on_finish_post: true
two_columns_layout: true


# Advanced Settings
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://apocalypse-dungeon.netlify.com" # the base hostname & protocol for your site
google_analytics: "UA-158734455-1"
language: "ko"
categories_folder: category
sent_message_url: "/contact/message-sent/"


# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/
collections:
  authors:
    output: true
paginate_path: "/page/:num/"
show_get_theme_btn: false
encoding: "utf-8"
use_logo: false

# Content paginator
paginate_content:
  enabled: true
  debug: false
  collections:
    - posts
  auto: false
  separator: "--page-break--"
  permalink: "/:num/"
  seo_canonical: true
  properties:
    part:
      is_generated: true
    last:
      is_generated: true
    single:
      is_generated: true

# SASS
sass:
  style: compressed

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-paginate-content

# Exclude my node related stuff
exclude: [
  'package.json',
  'package-lock.json',
  'src',
  'node_modules',
  'initpost.sh',
  'Gemfile',
  'Gemfile.lock',
  'gulpfile.js',
  'README.md'
]

# Theme
version: v3.0.2
