name: Apocalypse's Dungeon
title: A's Dungeon | 기타 등등등 잡동사니 블로그
description: Jekflix 베껴만들기
tags:
  - blog
  - netlify
  - programming
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: tags
    url: /tags
  - title: Contact
    url: /contact
  - title: Feed
    url: /feed.xml
email: psj89220@gmail.com
disqus_username: Apocalypse
